# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf3e4efe37f2baf99fe0c1606788d8f940ace19514698329b953d058b8ba1ba3e86ecd0bf25415ff31797cb0138d01c59d61a515a4226a77f2044751a815029e

test:
  secret_key_base: 3741d1a628ed6b24255017b127abacbc11d2d6261d6e1c4a85b425dcd49607998b3c2956380d2d98f44ea104fd3dc38184b1911d54680bf7ec930590b565d739

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
